test github actions

diff --git a/.github/workflows/packer_validate.yml b/.github/workflows/packer_validate.yml
--- a/.github/workflows/packer_validate.yml
+++ b/.github/workflows/packer_validate.yml
@@ -24,9 +24,11 @@ jobs:
       - name: Run packer fmt
         id: fmt
         run: |
-          set -e
           cd ./packer
-          packer fmt .
+          if ! packer fmt .; then
+            echo "Packer formatting failed"
+            exit 1
+          fi  
 
       - name: Run packer validate
         id: validate
